<?php
/**
 * @file
 * Add a dragndrop webform component.
 */

/**
 * Implements hook_webform_component_info.
 */
function webform_dragndrop_webform_component_info() {
  $components = array();
  $components['dragndrop'] = array(
    'label' => t('Drag and drop upload element'),
    'description' => t('An element to allow a user to drag and drop files.'),
    'features' => array(
      'required' => FALSE,
      'attachment' => TRUE,
    ),
    'file' => 'components/dragndrop.inc',
  );

  return $components;
}

/**
 * Implements hook_menu().
 */
function webform_dragndrop_menu() {
  $items['admin/config/webform-dragndrop-settings'] = array(
    'title' => 'Webform drag and drop settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('webform_dragndrop_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'webform_dragndrop.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}
